### ISSUE TITLE
Can't launch server

### ISSUE THREAD

**Issue by mrhead** [arkency/reactjs_koans#55]
Hey Guys,

I can't launch the local server on OSX El Capitan, is it possible that there is an issue with the `reactjs_koans` package? I've tried `npm rebuild`, installed latest `npm` version, but it is still the same.

```
# reactjs_koans/exercises/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.3.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@3.3.12
3 info using node@v5.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle reactjs_koans@0.0.4~prestart: reactjs_koans@0.0.4
6 silly lifecycle reactjs_koans@0.0.4~prestart: no script for prestart, continuing
7 info lifecycle reactjs_koans@0.0.4~start: reactjs_koans@0.0.4
8 verbose lifecycle reactjs_koans@0.0.4~start: unsafe-perm in lifecycle true
9 verbose lifecycle reactjs_koans@0.0.4~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/head/ruby/reactjs_koans/node_modules/.bin:/Users/head/.bin:/Users/head/.rbenv/shims:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/head/bin:/Applications/LibreOffice 2.app/Contents/MacOS:cli/bin
10 verbose lifecycle reactjs_koans@0.0.4~start: CWD: /Users/head/ruby/reactjs_koans
11 silly lifecycle reactjs_koans@0.0.4~start: Args: [ '-c',
11 silly lifecycle   'npm run compile > /dev/null 2>&1 && nodemon server.js' ]
12 silly lifecycle reactjs_koans@0.0.4~start: Returned: code: 1  signal: null
13 info lifecycle reactjs_koans@0.0.4~start: Failed to exec start script
14 verbose stack Error: reactjs_koans@0.0.4 start: `npm run compile > /dev/null 2>&1 && nodemon server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid reactjs_koans@0.0.4
16 verbose cwd /Users/head/ruby/reactjs_koans/exercises
17 error Darwin 15.2.0
18 error argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "run" "start"
19 error node v5.3.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error reactjs_koans@0.0.4 start: `npm run compile > /dev/null 2>&1 && nodemon server.js`
22 error Exit status 1
23 error Failed at the reactjs_koans@0.0.4 start script 'npm run compile > /dev/null 2>&1 && nodemon server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the reactjs_koans package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run compile > /dev/null 2>&1 && nodemon server.js
23 error You can get their info via:
23 error     npm owner ls reactjs_koans
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by voter101** [comment]
Can you show me the output after running `npm run compile` alone? Or is it a problem only with server?

**Comment by mrhead** [comment]
```
$ npm run compile

> reactjs_koans@0.0.4 compile /Users/head/ruby/reactjs_koans
> babel exercises --out-dir src > /dev/null 2>&1
```

It is only issue with the server, `npm run watch` is running fine.

**Comment by voter101** [comment]
@mrhead sorry for such a huge delay. Do you still have this problem?
