### ISSUE TITLE
events.js:141 - app crashed

### ISSUE THREAD

**Issue by unixconky** [arkency/reactjs_koans#67]
I tried to run: `npm run start` but I get:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at Server.listen (net.js:1369:5)
    at EventEmitter.listen (/home/user/ark/reactjs_koans/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/home/user/ark/reactjs_koans/server.js:28:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by andrzejkrzywda** [comment]
It seems that the port is already in use. Have you maybe started the koans server before and it's still running? Or maybe you're using some other software which listens at this port, like Java or Rails apps?

See this for possible solutions: http://stackoverflow.com/questions/4075287/node-express-eaddrinuse-address-already-in-use-kill-server

**Comment by unixconky** [comment]
You're right! Thank you.
